PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE DEPARTMENT (
ID INT PRIMARY KEY NOT NULL,
DEPT CHAR(50) NOT NULL,
EMP_ID INT NOT NULL
);
INSERT INTO DEPARTMENT VALUES(1,'IT Billing',1);
INSERT INTO DEPARTMENT VALUES(2,'Engineering',2);
INSERT INTO DEPARTMENT VALUES(3,'Finance',7);
INSERT INTO DEPARTMENT VALUES(4,'Engineering',3);
INSERT INTO DEPARTMENT VALUES(5,'Finance',4);
INSERT INTO DEPARTMENT VALUES(6,'Engineering',5);
INSERT INTO DEPARTMENT VALUES(7,'Finance',6);
CREATE TABLE COMPANY (
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL
);
INSERT INTO COMPANY VALUES(1,'Paul',32,'California',20000.0);
INSERT INTO COMPANY VALUES(2,'Allen',25,'Texas',20000.0);
INSERT INTO COMPANY VALUES(3,'Mark',25,'Norway',20000.0);
INSERT INTO COMPANY VALUES(4,'Teddy',23,'Rich-Mond',20000.0);
INSERT INTO COMPANY VALUES(5,'David',27,'Texas',20000.0);
INSERT INTO COMPANY VALUES(6,'Kim',22,'South-Hall',20000.0);
INSERT INTO COMPANY VALUES(7,'James',24,'Houston',10000.0);
INSERT INTO COMPANY VALUES(8,'Paul',24,'Houston',20000.0);
INSERT INTO COMPANY VALUES(9,'James',44,'Norway',5000.0);
INSERT INTO COMPANY VALUES(10,'James',45,'Texas',5000.0);
COMMIT;
